# Site settings
title: Jackie Kay
email: jacquelinekay1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackieokay.com" # the base hostname & protocol for your site
github_username:  jacquelinekay

# Build settings
markdown: kramdown
